#!/usr/bin/env python3

"""
Simple PDF watermark script using reportlab and PyPDF2.
Adds diagonal 'Generated by GitHub Actions - {author}' watermark.
"""

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from PyPDF2 import PdfReader, PdfWriter
import argparse
import io
from pathlib import Path

def add_watermark(input_pdf, output_pdf, author, watermark_text=None):
    if watermark_text is None:
        watermark_text = f'Generated by GitHub Actions - {author}'
    
    packet = io.BytesIO()
    # Create watermark overlay
    can = canvas.Canvas(packet, pagesize=letter)
    can.setFillAlpha(0.1)
    can.setFont("Helvetica", 30)
    can.rotate(45)
    can.drawString(200, -100, watermark_text)
    can.save()
    
    packet.seek(0)
    overlay = PdfReader(packet)
    
    reader = PdfReader(input_pdf)
    writer = PdfWriter()
    
    for page_num in range(len(reader.pages)):
        page = reader.pages[page_num]
        page.merge_page(overlay.pages[0])
        writer.add_page(page)
    
    with open(output_pdf, 'wb') as f:
        writer.write(f)
    
    print(f"Watermark added to {output_pdf}")
    return True

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Add watermark to PDF')
    parser.add_argument('input_pdf', help='Input PDF file')
    parser.add_argument('output_pdf', help='Output PDF file')
    parser.add_argument('author', help='Author name for watermark')
    args = parser.parse_args()
    
    add_watermark(args.input_pdf, args.output_pdf, args.author)
